import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import ResponsiveAppBar from "./components/ui/ResponsiveAppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveAppBar></ResponsiveAppBar>
        <main>{children}</main>
        <footer>
          <h3>Footer</h3>
        </footer>
      </body>
    </html>
  );
}
